aheckmann/m

bin/m

Added `shard` option to `m` to execute `mongos`. The binary already lives inside of the /bin directory, similar to `mongod`. 
Thanks.

Added mongos support

---

bin/m

check_current_version does not capture the version number of MongoDB 3.2.7 correctly (OSX, OpenSSL version) due to the regex capturing the OpenSSL version instead. This patch should fix it.

Fixed check_current_version to display version 3.2.7 with OpenSSL correctly

---

bin/m

The GNU cp command treats dir/ and dir as the same when using the recursive flag.
This leads to $M_PREFIX/bin/bin instead of $M_PREFIX/bin which means the intended mongo binaries are not in the path.

Generalize cp for BSD+GNU

---

README.md

- Update examples to non-EOL versions of MongoDB
- Proper case: s/mongodb/MongoDB/g

Update README with non-EOL examples

---

bin/m

Prior to this, running m when there are no installed versions
produced an error message:
m: line 140: versions: bad array subscript
Now it would report that no versions are installed:
No installed versions

Handle the case of no installed versions when listing installed versions

---

bin/m

This allows running m with bash -ex which is helpful for debugging.

Set -e compatibility

---

bin/m

Apt (the package manager) has had this default for as long as I remember
which is many years, and if it works for an operating system's
package manager it should also work for a Mongo version manager.
Also changed the return value of m when the user answers in the
negative, as the operation fails in that scenario.
This doesn't make a difference for #27 as there is still a prompt, but makes interactive use much more pleasant.

Default installation prompt to yes.

---

bin/m

This PR encapsulates the changes in #40 and https://github.com/devkev/m/tree/distros.
Although the utmost care was taken to ensure that it doesn't break things, this is a major change to `m` that will probably behave unexpectedly to people familiar with `m` over the years.
Short description of changes: This release will try to recognize the underlying Linux distro, and install distro-specific `mongod` version. This is done to enable SSL support, which was previously not available to `m`-installed `mongod` in Linux.
The supported distro list tracks pretty closely the [supported platforms in the production notes](https://docs.mongodb.com/manual/administration/production-notes/#supported-platforms):
- Amazon Linux 1 & 2
- Debian 7, 8, 9
- SUSE Linux
- Ubuntu 12.04, 14.04, 16.04, 18.04
For …

Linux distro-specific support

---

bin/m

Ubuntu mapping based on https://en.wikipedia.org/wiki/Linux_Mint_version_history#Release_history
Added support for Linux Mint 17.x, 18.x and 19.x.

Add distro detection for Linux Mint

---

bin/m

`--legacy` must come after the requested version, not before it,
otherwise m will try to install a version `--legacy`.

correct placement of the `--legacy` parameter

---

bin/m

The enterprise installation appears to be broken on master because `tarball` is never assigned. This PR fixes that and also adds `debian10` as a known distro for 4.4 server. Lastly it changes the download host from downloads.10gen.com to downloads.mongodb.com which is what the download center currently references.
Tested with 4.3.4 and 4.3.4-ent on Debian 10 and Ubuntu 18.04.

Add Debian 10 support, unbreak enterprise installation

---

README.md
bin/m

Adds a tools command with `stable`, `ls`, and `installed` subcommands. The server/shell and database tools are now versioned independently. I've manually tested on MacOS and several Linux distros.
This PR isn't perfect. You can't filter by major/minor version. So `m tools ls X.Y` won't work. Also `m tools X.Y` won't install the latest patch of X.Y, you have to specify the whole version.
Fixes #62

TOOLS-2678 Add support for standalone database tools

---

bin/m

MongoDB 4.4 changes the output of `mongod --version`, which breaks active version detection when an enterprise version is active:
```
$ m
ο 4.2.12-ent 
4.4.3-ent 
$ mongod --version
db version v4.2.12
git version: 5593fd8e33b60c75802edab304e23998fa0ce8a5
allocator: system
modules: enterprise 
build environment:
distarch: x86_64
target_arch: x86_64
$ m 4.4.3-ent
Activating 4.4.3-ent
$ mongod --version
db version v4.4.3
Build Info: {
"version": "4.4.3",
"gitVersion": "913d6b62acfbb344dde1b116f4161360acd8fd13",
"modules": [
"enterprise"
],
"allocator": "system",
"environment": {
"distarch": "x86_64",
"target_arch": "x86_64"
}
}
$ m
4.2.12-ent 
4.4.3-ent 
```
I'm not sure the solution suggested here is free of unwanted side effects, but it's the best I could come up with. `egrep` works line …

Fix detection of enterprise versions in 4.4+

---

bin/m

-depth N is only supported in BSD, -min/maxdepth seems to be supported everywhere. Placing them before other options also removes a warning:
```
$ find /home/ubuntu/.local/m/versions -type d -depth
find: warning: you have specified the -depth option after a non-option argument -type, but options are not positional (-depth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.
find: paths must precede expression: `1'
$ find /home/ubuntu/.local/m/versions -maxdepth 1 -mindepth 1 -type d
/home/ubuntu/.local/m/versions/5.0.5
/home/ubuntu/.local/m/versions/5.2.0-rc2
/home/ubuntu/.local/m/versions/5.1.1
```

Use -(min|max)depth in find instead of -depth

---

bin/m

Today I had a fluke DNS failure on the tools installation step and `m` reported a success status code. I was using it to gain access to the tools in a container build, so the whole container build kept on trucking. I realize this is mostly a tool for dev environments, but I thought I'd contribute a check so that the script fails properly in this situation.
Thanks for creating and maintaining `m`! It is greatly appreciated.

report failure of tools installation

---

bin/m

Since GNU grep release 3.8 the egrep command prints a warning to STDERR that 'egrep is obsolescent', which is annoying. This commit change m to use `grep -E` instead, which is supported by both BSD and GNU grep.
Announcement of change to GNU egrep:
https://git.savannah.gnu.org/cgit/grep.git/tree/NEWS#n75
The GNU egrep warning can be found here:
https://git.savannah.gnu.org/cgit/grep.git/tree/src/egrep.sh#n3

fix error message when using GNU egrep

---

History.md
bin/m
package.json

1.8.5 / 2023-09-13
==================
* Fix error message when using GNU egrep (@charlievieth)
* Docs: git:// should be replaced with https:// (@michaelstruening)

Update for 1.8.5 release

---

bin/m

When `wget` is selected as the binary for `GET`, it uses the `-q` ("quiet") option which suppresses output. However, when `curl` is used, it uses the `-#` option which prints a progress bar during download. 
This change replaces the `-#` option to `curl` with `-s` ("silent") instead. This makes the behavior consistent with what happens when `wget` is used; in many cases (such as using `m` to download a specific version of mongo for running tests in CI) the progress bar can generate a lot of spammy log output, so it's better off without it IMO.

Use "curl -s" (silent) instead of "curl -#"

---

bin/m

Pop_OS! is among the top 10 Linux distribution [according to Distrowatch](https://distrowatch.com/index.php?dataspan=52) and is based on Ubuntu

Add support for Pop_OS! linux distribution

---

bin/m

`m` doesn't download the correct binaries for Amazon Linux 2023. This is problematic since those binaries have been built to support `OpenSSL 3`. Instead, we fall back to the Amazon Linux 2 binaries, which support `OpenSSL 1` and therefore don't even run.

Add support for Amazon Linux 2023

---

bin/m

This should prevent invocations of m from getting rate limited on GitHub rest api when accessing the tags API for public repos anonymously.
In the process of troubleshooting this, I allow curl errors to bubble up to the terminal to help troubleshoot.
I'm not handling wget right now because curl is more common so will be preferred also because wget's -nv option still prints a basic success message. Also--curl is still used unconditionally for getting tags of mongodb/mongo-tools, so it's effectively required.

Use GitHub token from the environment for API requests if present
